//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe.MyDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public string IDnhanVien { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<float> Luong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
