//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe.MyDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBanHang
    {
        public string IDhoaDonBH { get; set; }
        public string IDnhanVien { get; set; }
        public System.DateTime Ngaytao { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
