//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe.MyDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginNhanVien
    {
        public string IDNhanVien { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public bool Permission { get; set; }
        public System.DateTime Ngaytao { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
