//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe.MyDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyCafeEntities : DbContext
    {
        public QuanLyCafeEntities(string connectionString)
            : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ban> Bans { get; set; }
        public virtual DbSet<BangLuong> BangLuongs { get; set; }
        public virtual DbSet<ChiTietHoaDonBanHang> ChiTietHoaDonBanHangs { get; set; }
        public virtual DbSet<ChiTietHoaDonNhapHang> ChiTietHoaDonNhapHangs { get; set; }
        public virtual DbSet<HoaDonBanHang> HoaDonBanHangs { get; set; }
        public virtual DbSet<HoaDonNhapHang> HoaDonNhapHangs { get; set; }
        public virtual DbSet<KhoHang> KhoHangs { get; set; }
        public virtual DbSet<LoaiThucDon> LoaiThucDons { get; set; }
        public virtual DbSet<LoginNhanVien> LoginNhanViens { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<ThanhVien> ThanhViens { get; set; }
        public virtual DbSet<ThucDon> ThucDons { get; set; }
        public virtual DbSet<BaoCaoBanHang> BaoCaoBanHangs { get; set; }
        public virtual DbSet<BaoCaoNhapHang> BaoCaoNhapHangs { get; set; }
    
        [DbFunction("QuanLyCafeEntities", "f_ChiTietHoaDonBanHang")]
        public virtual IQueryable<f_ChiTietHoaDonBanHang_Result> f_ChiTietHoaDonBanHang(string iDHoaDonBH)
        {
            var iDHoaDonBHParameter = iDHoaDonBH != null ?
                new ObjectParameter("IDHoaDonBH", iDHoaDonBH) :
                new ObjectParameter("IDHoaDonBH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_ChiTietHoaDonBanHang_Result>("[QuanLyCafeEntities].[f_ChiTietHoaDonBanHang](@IDHoaDonBH)", iDHoaDonBHParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_ChiTietHoaDonNhapHang")]
        public virtual IQueryable<f_ChiTietHoaDonNhapHang_Result> f_ChiTietHoaDonNhapHang(string iDHoaDonNH)
        {
            var iDHoaDonNHParameter = iDHoaDonNH != null ?
                new ObjectParameter("IDHoaDonNH", iDHoaDonNH) :
                new ObjectParameter("IDHoaDonNH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_ChiTietHoaDonNhapHang_Result>("[QuanLyCafeEntities].[f_ChiTietHoaDonNhapHang](@IDHoaDonNH)", iDHoaDonNHParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_DoanhThu")]
        public virtual IQueryable<f_DoanhThu_Result> f_DoanhThu(Nullable<System.DateTime> daybegin, Nullable<System.DateTime> dayend)
        {
            var daybeginParameter = daybegin.HasValue ?
                new ObjectParameter("daybegin", daybegin) :
                new ObjectParameter("daybegin", typeof(System.DateTime));
    
            var dayendParameter = dayend.HasValue ?
                new ObjectParameter("dayend", dayend) :
                new ObjectParameter("dayend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThu_Result>("[QuanLyCafeEntities].[f_DoanhThu](@daybegin, @dayend)", daybeginParameter, dayendParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_DoanhThuNgay_BanHang")]
        public virtual IQueryable<f_DoanhThuNgay_BanHang_Result> f_DoanhThuNgay_BanHang(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThuNgay_BanHang_Result>("[QuanLyCafeEntities].[f_DoanhThuNgay_BanHang](@date)", dateParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_DoanhThuNgay_NhapHang")]
        public virtual IQueryable<f_DoanhThuNgay_NhapHang_Result> f_DoanhThuNgay_NhapHang(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThuNgay_NhapHang_Result>("[QuanLyCafeEntities].[f_DoanhThuNgay_NhapHang](@date)", dateParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_DoanhThuThang")]
        public virtual IQueryable<f_DoanhThuThang_Result> f_DoanhThuThang(Nullable<int> monthBegin, Nullable<int> yearBegin, Nullable<int> monthEnd, Nullable<int> yearEnd)
        {
            var monthBeginParameter = monthBegin.HasValue ?
                new ObjectParameter("monthBegin", monthBegin) :
                new ObjectParameter("monthBegin", typeof(int));
    
            var yearBeginParameter = yearBegin.HasValue ?
                new ObjectParameter("yearBegin", yearBegin) :
                new ObjectParameter("yearBegin", typeof(int));
    
            var monthEndParameter = monthEnd.HasValue ?
                new ObjectParameter("monthEnd", monthEnd) :
                new ObjectParameter("monthEnd", typeof(int));
    
            var yearEndParameter = yearEnd.HasValue ?
                new ObjectParameter("yearEnd", yearEnd) :
                new ObjectParameter("yearEnd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThuThang_Result>("[QuanLyCafeEntities].[f_DoanhThuThang](@monthBegin, @yearBegin, @monthEnd, @yearEnd)", monthBeginParameter, yearBeginParameter, monthEndParameter, yearEndParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_KiemTraLoGin")]
        public virtual IQueryable<f_KiemTraLoGin_Result> f_KiemTraLoGin(string loginName, string password)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_KiemTraLoGin_Result>("[QuanLyCafeEntities].[f_KiemTraLoGin](@LoginName, @Password)", loginNameParameter, passwordParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LayCTHoaDonBanHang")]
        public virtual IQueryable<f_LayCTHoaDonBanHang_Result> f_LayCTHoaDonBanHang(string iDhoaDonBH)
        {
            var iDhoaDonBHParameter = iDhoaDonBH != null ?
                new ObjectParameter("IDhoaDonBH", iDhoaDonBH) :
                new ObjectParameter("IDhoaDonBH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayCTHoaDonBanHang_Result>("[QuanLyCafeEntities].[f_LayCTHoaDonBanHang](@IDhoaDonBH)", iDhoaDonBHParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LayCTHoaDonNhapHang")]
        public virtual IQueryable<f_LayCTHoaDonNhapHang_Result> f_LayCTHoaDonNhapHang(string iDhoaDonNH)
        {
            var iDhoaDonNHParameter = iDhoaDonNH != null ?
                new ObjectParameter("IDhoaDonNH", iDhoaDonNH) :
                new ObjectParameter("IDhoaDonNH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayCTHoaDonNhapHang_Result>("[QuanLyCafeEntities].[f_LayCTHoaDonNhapHang](@IDhoaDonNH)", iDhoaDonNHParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LayCTLoaiThucDon")]
        public virtual IQueryable<f_LayCTLoaiThucDon_Result> f_LayCTLoaiThucDon(string iDloaiThucDon)
        {
            var iDloaiThucDonParameter = iDloaiThucDon != null ?
                new ObjectParameter("IDloaiThucDon", iDloaiThucDon) :
                new ObjectParameter("IDloaiThucDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayCTLoaiThucDon_Result>("[QuanLyCafeEntities].[f_LayCTLoaiThucDon](@IDloaiThucDon)", iDloaiThucDonParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LaySoLuongHoaDonNhanVienThanhToanTheoNgay")]
        public virtual IQueryable<f_LaySoLuongHoaDonNhanVienThanhToanTheoNgay_Result> f_LaySoLuongHoaDonNhanVienThanhToanTheoNgay(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LaySoLuongHoaDonNhanVienThanhToanTheoNgay_Result>("[QuanLyCafeEntities].[f_LaySoLuongHoaDonNhanVienThanhToanTheoNgay](@day, @month, @year)", dayParameter, monthParameter, yearParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LaySoLuongHoaDonThanhVienThanhToanTheoNgay")]
        public virtual IQueryable<f_LaySoLuongHoaDonThanhVienThanhToanTheoNgay_Result> f_LaySoLuongHoaDonThanhVienThanhToanTheoNgay(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LaySoLuongHoaDonThanhVienThanhToanTheoNgay_Result>("[QuanLyCafeEntities].[f_LaySoLuongHoaDonThanhVienThanhToanTheoNgay](@day, @month, @year)", dayParameter, monthParameter, yearParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LaySoLuongThucDonTheoNgay")]
        public virtual IQueryable<f_LaySoLuongThucDonTheoNgay_Result> f_LaySoLuongThucDonTheoNgay(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LaySoLuongThucDonTheoNgay_Result>("[QuanLyCafeEntities].[f_LaySoLuongThucDonTheoNgay](@day, @month, @year)", dayParameter, monthParameter, yearParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LayThanhVienTheoBan")]
        public virtual IQueryable<f_LayThanhVienTheoBan_Result> f_LayThanhVienTheoBan(string iDban)
        {
            var iDbanParameter = iDban != null ?
                new ObjectParameter("IDban", iDban) :
                new ObjectParameter("IDban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayThanhVienTheoBan_Result>("[QuanLyCafeEntities].[f_LayThanhVienTheoBan](@IDban)", iDbanParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_LayThongTinNhanVien")]
        public virtual IQueryable<f_LayThongTinNhanVien_Result> f_LayThongTinNhanVien(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LayThongTinNhanVien_Result>("[QuanLyCafeEntities].[f_LayThongTinNhanVien](@ID)", iDParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_TaoIDHoaDonBanHangMoi")]
        public virtual IQueryable<f_TaoIDHoaDonBanHangMoi_Result> f_TaoIDHoaDonBanHangMoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TaoIDHoaDonBanHangMoi_Result>("[QuanLyCafeEntities].[f_TaoIDHoaDonBanHangMoi]()");
        }
    
        [DbFunction("QuanLyCafeEntities", "f_TaoIDHoaDonNhapHangMoi")]
        public virtual IQueryable<f_TaoIDHoaDonNhapHangMoi_Result> f_TaoIDHoaDonNhapHangMoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TaoIDHoaDonNhapHangMoi_Result>("[QuanLyCafeEntities].[f_TaoIDHoaDonNhapHangMoi]()");
        }
    
        [DbFunction("QuanLyCafeEntities", "f_TinhTienHoaDonBH")]
        public virtual IQueryable<f_TinhTienHoaDonBH_Result> f_TinhTienHoaDonBH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TinhTienHoaDonBH_Result>("[QuanLyCafeEntities].[f_TinhTienHoaDonBH]()");
        }
    
        [DbFunction("QuanLyCafeEntities", "f_TinhTienHoaDonNH")]
        public virtual IQueryable<f_TinhTienHoaDonNH_Result> f_TinhTienHoaDonNH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TinhTienHoaDonNH_Result>("[QuanLyCafeEntities].[f_TinhTienHoaDonNH]()");
        }
    
        [DbFunction("QuanLyCafeEntities", "f_TopNhanVien")]
        public virtual IQueryable<f_TopNhanVien_Result> f_TopNhanVien(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TopNhanVien_Result>("[QuanLyCafeEntities].[f_TopNhanVien](@day, @month, @year)", dayParameter, monthParameter, yearParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_TopThanhVien")]
        public virtual IQueryable<f_TopThanhVien_Result> f_TopThanhVien(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TopThanhVien_Result>("[QuanLyCafeEntities].[f_TopThanhVien](@day, @month, @year)", dayParameter, monthParameter, yearParameter);
        }
    
        [DbFunction("QuanLyCafeEntities", "f_TopThucDon")]
        public virtual IQueryable<f_TopThucDon_Result> f_TopThucDon(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TopThucDon_Result>("[QuanLyCafeEntities].[f_TopThucDon](@day, @month, @year)", dayParameter, monthParameter, yearParameter);
        }
    
        public virtual int sp_Delete_Ban(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_Ban", iDParameter);
        }
    
        public virtual int sp_Delete_BangLuong(string iDnhanVien, Nullable<int> thang, Nullable<int> nam)
        {
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_BangLuong", iDnhanVienParameter, thangParameter, namParameter);
        }
    
        public virtual int sp_Delete_ChiTietHoaDonBanHang(string iDhoaDonBH, string iDthucDon)
        {
            var iDhoaDonBHParameter = iDhoaDonBH != null ?
                new ObjectParameter("IDhoaDonBH", iDhoaDonBH) :
                new ObjectParameter("IDhoaDonBH", typeof(string));
    
            var iDthucDonParameter = iDthucDon != null ?
                new ObjectParameter("IDthucDon", iDthucDon) :
                new ObjectParameter("IDthucDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_ChiTietHoaDonBanHang", iDhoaDonBHParameter, iDthucDonParameter);
        }
    
        public virtual int sp_Delete_ChiTietHoaDonNhapHang(string iDhoaDonNH, string iDhang)
        {
            var iDhoaDonNHParameter = iDhoaDonNH != null ?
                new ObjectParameter("IDhoaDonNH", iDhoaDonNH) :
                new ObjectParameter("IDhoaDonNH", typeof(string));
    
            var iDhangParameter = iDhang != null ?
                new ObjectParameter("IDhang", iDhang) :
                new ObjectParameter("IDhang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_ChiTietHoaDonNhapHang", iDhoaDonNHParameter, iDhangParameter);
        }
    
        public virtual int sp_Delete_HoaDonBanHang(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_HoaDonBanHang", iDParameter);
        }
    
        public virtual int sp_Delete_HoaDonNhapHang(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_HoaDonNhapHang", iDParameter);
        }
    
        public virtual int sp_Delete_KhoHang(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_KhoHang", iDParameter);
        }
    
        public virtual int sp_Delete_LoginNhanVien(string loginName)
        {
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_LoginNhanVien", loginNameParameter);
        }
    
        public virtual int sp_Delete_NhanVien(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_NhanVien", iDParameter);
        }
    
        public virtual int sp_Delete_ThanhVien(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_ThanhVien", iDParameter);
        }
    
        public virtual int sp_Delete_ThucDon(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_ThucDon", iDParameter);
        }
    
        public virtual int sp_Insert_Ban(string iD, string tenBan, Nullable<int> maxSoLuong)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenBanParameter = tenBan != null ?
                new ObjectParameter("TenBan", tenBan) :
                new ObjectParameter("TenBan", typeof(string));
    
            var maxSoLuongParameter = maxSoLuong.HasValue ?
                new ObjectParameter("MaxSoLuong", maxSoLuong) :
                new ObjectParameter("MaxSoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_Ban", iDParameter, tenBanParameter, maxSoLuongParameter);
        }
    
        public virtual int sp_Insert_BangLuong(string iD, Nullable<int> thang, Nullable<int> nam, Nullable<float> luong)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_BangLuong", iDParameter, thangParameter, namParameter, luongParameter);
        }
    
        public virtual int sp_Insert_ChiTietHoaDonBanHang(string iDhoaDonBH, string iDthucDon, Nullable<int> soLuong)
        {
            var iDhoaDonBHParameter = iDhoaDonBH != null ?
                new ObjectParameter("IDhoaDonBH", iDhoaDonBH) :
                new ObjectParameter("IDhoaDonBH", typeof(string));
    
            var iDthucDonParameter = iDthucDon != null ?
                new ObjectParameter("IDthucDon", iDthucDon) :
                new ObjectParameter("IDthucDon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_ChiTietHoaDonBanHang", iDhoaDonBHParameter, iDthucDonParameter, soLuongParameter);
        }
    
        public virtual int sp_Insert_ChiTietHoaDonNhapHang(string iDhoaDonNH, string iDhang, Nullable<int> soLuong)
        {
            var iDhoaDonNHParameter = iDhoaDonNH != null ?
                new ObjectParameter("IDhoaDonNH", iDhoaDonNH) :
                new ObjectParameter("IDhoaDonNH", typeof(string));
    
            var iDhangParameter = iDhang != null ?
                new ObjectParameter("IDhang", iDhang) :
                new ObjectParameter("IDhang", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_ChiTietHoaDonNhapHang", iDhoaDonNHParameter, iDhangParameter, soLuongParameter);
        }
    
        public virtual int sp_Insert_HoaDonBanHang(string iD, string iDnhanVien, string iDthanhVien, string iDban, Nullable<System.DateTime> ngaytao)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var iDthanhVienParameter = iDthanhVien != null ?
                new ObjectParameter("IDthanhVien", iDthanhVien) :
                new ObjectParameter("IDthanhVien", typeof(string));
    
            var iDbanParameter = iDban != null ?
                new ObjectParameter("IDban", iDban) :
                new ObjectParameter("IDban", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("Ngaytao", ngaytao) :
                new ObjectParameter("Ngaytao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_HoaDonBanHang", iDParameter, iDnhanVienParameter, iDthanhVienParameter, iDbanParameter, ngaytaoParameter);
        }
    
        public virtual int sp_Insert_HoaDonNhapHang(string iD, string iDnhanVien, Nullable<System.DateTime> ngayTao)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_HoaDonNhapHang", iDParameter, iDnhanVienParameter, ngayTaoParameter);
        }
    
        public virtual int sp_Insert_KhoHang(string iD, string ten, string donViTinh, Nullable<int> soLuong, Nullable<float> donGia)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_KhoHang", iDParameter, tenParameter, donViTinhParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int sp_Insert_LoginNhanVien(string iDNhanVien, string loginName, string password, Nullable<bool> permission, Nullable<System.DateTime> ngaytao)
        {
            var iDNhanVienParameter = iDNhanVien != null ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(string));
    
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var permissionParameter = permission.HasValue ?
                new ObjectParameter("Permission", permission) :
                new ObjectParameter("Permission", typeof(bool));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("Ngaytao", ngaytao) :
                new ObjectParameter("Ngaytao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_LoginNhanVien", iDNhanVienParameter, loginNameParameter, passwordParameter, permissionParameter, ngaytaoParameter);
        }
    
        public virtual int sp_Insert_NhanVien(string iD, string hoTen, string sDT, string cMND, string diaChi, Nullable<System.DateTime> ngayVaoLam, Nullable<System.DateTime> ngayNghiViec, Nullable<float> luongCoBan)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var ngayNghiViecParameter = ngayNghiViec.HasValue ?
                new ObjectParameter("NgayNghiViec", ngayNghiViec) :
                new ObjectParameter("NgayNghiViec", typeof(System.DateTime));
    
            var luongCoBanParameter = luongCoBan.HasValue ?
                new ObjectParameter("LuongCoBan", luongCoBan) :
                new ObjectParameter("LuongCoBan", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_NhanVien", iDParameter, hoTenParameter, sDTParameter, cMNDParameter, diaChiParameter, ngayVaoLamParameter, ngayNghiViecParameter, luongCoBanParameter);
        }
    
        public virtual int sp_Insert_ThanhVien(string iD, string hoTen, string sDT, string email, string cMND, string diaChi, Nullable<System.DateTime> ngayTao)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_ThanhVien", iDParameter, hoTenParameter, sDTParameter, emailParameter, cMNDParameter, diaChiParameter, ngayTaoParameter);
        }
    
        public virtual int sp_Insert_ThucDon(string iD, string ten, string donViTinh, Nullable<float> donGia, string iDloaiThucDon)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(float));
    
            var iDloaiThucDonParameter = iDloaiThucDon != null ?
                new ObjectParameter("IDloaiThucDon", iDloaiThucDon) :
                new ObjectParameter("IDloaiThucDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_ThucDon", iDParameter, tenParameter, donViTinhParameter, donGiaParameter, iDloaiThucDonParameter);
        }
    
        public virtual int sp_Update_Ban(string iD, string tenBan, Nullable<int> soLuong, Nullable<int> maxSoLuong)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenBanParameter = tenBan != null ?
                new ObjectParameter("TenBan", tenBan) :
                new ObjectParameter("TenBan", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var maxSoLuongParameter = maxSoLuong.HasValue ?
                new ObjectParameter("MaxSoLuong", maxSoLuong) :
                new ObjectParameter("MaxSoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_Ban", iDParameter, tenBanParameter, soLuongParameter, maxSoLuongParameter);
        }
    
        public virtual int sp_Update_BangLuong(string iDnhanVien, Nullable<int> thang, Nullable<int> nam, Nullable<float> luong)
        {
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_BangLuong", iDnhanVienParameter, thangParameter, namParameter, luongParameter);
        }
    
        public virtual int sp_Update_ChiTietHoaDonBanHang(string iDhoaDonBH, string iDthucDon, Nullable<int> soLuong)
        {
            var iDhoaDonBHParameter = iDhoaDonBH != null ?
                new ObjectParameter("IDhoaDonBH", iDhoaDonBH) :
                new ObjectParameter("IDhoaDonBH", typeof(string));
    
            var iDthucDonParameter = iDthucDon != null ?
                new ObjectParameter("IDthucDon", iDthucDon) :
                new ObjectParameter("IDthucDon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_ChiTietHoaDonBanHang", iDhoaDonBHParameter, iDthucDonParameter, soLuongParameter);
        }
    
        public virtual int sp_Update_ChiTietHoaDonNhapHang(string iDhoaDonNH, string iDhang, Nullable<int> soLuong)
        {
            var iDhoaDonNHParameter = iDhoaDonNH != null ?
                new ObjectParameter("IDhoaDonNH", iDhoaDonNH) :
                new ObjectParameter("IDhoaDonNH", typeof(string));
    
            var iDhangParameter = iDhang != null ?
                new ObjectParameter("IDhang", iDhang) :
                new ObjectParameter("IDhang", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_ChiTietHoaDonNhapHang", iDhoaDonNHParameter, iDhangParameter, soLuongParameter);
        }
    
        public virtual int sp_Update_HoaDonBanHang(string iD, string iDnhanVien, string iDthanhVien, string iDban, Nullable<System.DateTime> ngaytao, Nullable<bool> daThanhToan)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var iDthanhVienParameter = iDthanhVien != null ?
                new ObjectParameter("IDthanhVien", iDthanhVien) :
                new ObjectParameter("IDthanhVien", typeof(string));
    
            var iDbanParameter = iDban != null ?
                new ObjectParameter("IDban", iDban) :
                new ObjectParameter("IDban", typeof(string));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("Ngaytao", ngaytao) :
                new ObjectParameter("Ngaytao", typeof(System.DateTime));
    
            var daThanhToanParameter = daThanhToan.HasValue ?
                new ObjectParameter("DaThanhToan", daThanhToan) :
                new ObjectParameter("DaThanhToan", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_HoaDonBanHang", iDParameter, iDnhanVienParameter, iDthanhVienParameter, iDbanParameter, ngaytaoParameter, daThanhToanParameter);
        }
    
        public virtual int sp_Update_HoaDonNhapHang(string iD, string iDnhanVien, Nullable<System.DateTime> ngayTao)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var iDnhanVienParameter = iDnhanVien != null ?
                new ObjectParameter("IDnhanVien", iDnhanVien) :
                new ObjectParameter("IDnhanVien", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_HoaDonNhapHang", iDParameter, iDnhanVienParameter, ngayTaoParameter);
        }
    
        public virtual int sp_Update_KhoHang(string iD, string ten, string donViTinh, Nullable<int> soLuong, Nullable<float> donGia)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_KhoHang", iDParameter, tenParameter, donViTinhParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int sp_Update_LoginNhanVien(string iDNhanVien, string loginName, string password, Nullable<bool> permission, Nullable<System.DateTime> ngaytao)
        {
            var iDNhanVienParameter = iDNhanVien != null ?
                new ObjectParameter("IDNhanVien", iDNhanVien) :
                new ObjectParameter("IDNhanVien", typeof(string));
    
            var loginNameParameter = loginName != null ?
                new ObjectParameter("LoginName", loginName) :
                new ObjectParameter("LoginName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var permissionParameter = permission.HasValue ?
                new ObjectParameter("Permission", permission) :
                new ObjectParameter("Permission", typeof(bool));
    
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("Ngaytao", ngaytao) :
                new ObjectParameter("Ngaytao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_LoginNhanVien", iDNhanVienParameter, loginNameParameter, passwordParameter, permissionParameter, ngaytaoParameter);
        }
    
        public virtual int sp_Update_NhanVien(string iD, string hoTen, string sDT, string cMND, string diaChi, Nullable<System.DateTime> ngayVaoLam, Nullable<System.DateTime> ngayNghiViec, Nullable<float> luongCoBan)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var ngayVaoLamParameter = ngayVaoLam.HasValue ?
                new ObjectParameter("NgayVaoLam", ngayVaoLam) :
                new ObjectParameter("NgayVaoLam", typeof(System.DateTime));
    
            var ngayNghiViecParameter = ngayNghiViec.HasValue ?
                new ObjectParameter("NgayNghiViec", ngayNghiViec) :
                new ObjectParameter("NgayNghiViec", typeof(System.DateTime));
    
            var luongCoBanParameter = luongCoBan.HasValue ?
                new ObjectParameter("LuongCoBan", luongCoBan) :
                new ObjectParameter("LuongCoBan", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_NhanVien", iDParameter, hoTenParameter, sDTParameter, cMNDParameter, diaChiParameter, ngayVaoLamParameter, ngayNghiViecParameter, luongCoBanParameter);
        }
    
        public virtual int sp_Update_ThanhVien(string iD, string hoTen, string sDT, string email, string cMND, string diaChi, Nullable<System.DateTime> ngayTao)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_ThanhVien", iDParameter, hoTenParameter, sDTParameter, emailParameter, cMNDParameter, diaChiParameter, ngayTaoParameter);
        }
    
        public virtual int sp_Update_ThucDon(string iD, string ten, string donViTinh, Nullable<float> donGia, string iDloaiThucDon)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(float));
    
            var iDloaiThucDonParameter = iDloaiThucDon != null ?
                new ObjectParameter("IDloaiThucDon", iDloaiThucDon) :
                new ObjectParameter("IDloaiThucDon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_ThucDon", iDParameter, tenParameter, donViTinhParameter, donGiaParameter, iDloaiThucDonParameter);
        }
    
        public virtual int sp_Update_TrangThaiHoanDonBanHang(string iD, Nullable<bool> daThanhToan)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var daThanhToanParameter = daThanhToan.HasValue ?
                new ObjectParameter("DaThanhToan", daThanhToan) :
                new ObjectParameter("DaThanhToan", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_TrangThaiHoanDonBanHang", iDParameter, daThanhToanParameter);
        }
    }
}
