//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe.MyDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_HoaDonNhapHang
    {
        public string ID { get; set; }
        public string IDnhanVien { get; set; }
        public System.DateTime NgayTao { get; set; }
    }
}
