//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe.MyDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ThucDon
    {
        public string ID { get; set; }
        public string Ten { get; set; }
        public string DonViTinh { get; set; }
        public float DonGia { get; set; }
    }
}
